-- 005_xref.sql — перекодировка участка и все ключи между схемами.
-- Нумерация: docs/plan.md стр. 565 нумерует пять файлов схемы 001…005, это последний.
-- В docs/HLD.md разд. 5.4 тот же файл назван 010_xref — там список из двенадцати
-- миграций, который план заменил. Верен план. Накатывается ПОСЛЕДНЕЙ:
--   001_assets.sql -> 002_geo.sql -> 003_permits.sql -> 004_events.sql -> этот файл.
--
-- Зачем отдельный файл. Один и тот же участок коллектора в четырёх схемах зовётся
-- по-разному (docs/HLD.md разд. 5.3): smvu/feat/pred — section_id integer,
-- geo — object_id uuid, asset — func_location.id bigint, permit — location.id bigint.
-- Таблица перекодировки ссылается сразу на три схемы, а на неё ссылаются ещё семь
-- таблиц из четвёртой. Положить её в любой из четырёх файлов нельзя: файл начнёт
-- ссылаться на то, чего при его накатывании ещё нет. Сюда же собраны три ключа,
-- которые упёрлись в порядок файлов: заявка -> прогноз, операция заказа -> наряд,
-- блокировка датчика под наряд -> датчик.

CREATE SCHEMA IF NOT EXISTS ref;   -- уже есть после 001_assets.sql, но файл обязан быть самодостаточным

-- ---------------------------------------------------------------------------
-- 1. Участок: один короткий ключ на четыре длинных
-- ---------------------------------------------------------------------------
-- section_id — integer, а не uuid, потому что стоит в горячем пути: 18 млн строк
-- событий и 5,4 млн строк свёртки. 4 байта против 16 — 216 МБ разницы в куче
-- и столько же в индексах (docs/HLD.md разд. 5.3).
--
-- Участок, для которого перекодировки ещё нет. В выгрузке СМВУ адреса нет вовсе:
-- данные обезличены на стороне источника, объекты называются «объект Альфа».
-- Место собирается из двух колонок справочника каналов разборщиком
-- code/tag_to_section.py: коллектор из тега до дефиса, пикет из названия датчика.
-- Загрузчик на каждую новую пару заводит строку здесь с одним только smvu_key,
-- а три ссылки оставляет пустыми, пока не придёт геометрия. Так историческая загрузка
-- не падает на неизвестном участке, строка не теряется и не получает координату (0,0):
--
--   INSERT INTO ref.object_xref (smvu_key) VALUES ($1)
--   ON CONFLICT (smvu_key) DO UPDATE SET smvu_key = excluded.smvu_key
--   RETURNING section_id;
--
-- GENERATED BY DEFAULT, а не ALWAYS: если заказчик отдаст реестр участков со своими
-- номерами, их можно вставить как есть, а новые адреса дальше нумерует база.
CREATE TABLE ref.object_xref (
    section_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Три ссылки в чужие схемы. ON DELETE SET NULL: участок с историей событий
    -- переживает удаление своей записи в геореестре, ТОиР или нарядах.
    geo_object_id      uuid   UNIQUE REFERENCES geo.geo_object(object_id)     ON DELETE SET NULL,
    func_location_id   bigint UNIQUE REFERENCES asset.func_location(id)       ON DELETE SET NULL,
    permit_location_id bigint UNIQUE REFERENCES permit.location(id)           ON DELETE SET NULL,
    -- Ключ участка из выгрузки СМВУ: «коллектор:пикет», например "847:106". Собирается
    -- code/tag_to_section.py. На выгрузке от 09.09.2026 таких пар 3173 на 30 коллекторах.
    -- Пара, а не один пикет: пикетаж у каждого коллектора свой и начинается с нуля,
    -- из 32 коллекторов 27 имеют канал на ПК0. Раньше здесь стоял smvu_address —
    -- адрес текстом, которого в выгрузке не оказалось.
    smvu_key           text   UNIQUE,
    inventory_no       text,              -- номер по реестру ОЭ, для сверки руками
    -- Строка без единого опознавательного признака бессмысленна.
    CHECK (num_nonnulls(geo_object_id, func_location_id, permit_location_id,
                        smvu_key, inventory_no) > 0)
);

COMMENT ON TABLE ref.object_xref IS
    'Перекодировка участка коллектора: канонический section_id против ключей geo, asset, permit и ключа коллектор:пикет из СМВУ';

-- ---------------------------------------------------------------------------
-- 2. Ключи section_id -> ref.object_xref
-- ---------------------------------------------------------------------------
-- ON DELETE не указан = NO ACTION: участок с событиями или прогнозами удалить
-- нельзя, сначала надо решить, куда девать его историю.
ALTER TABLE smvu.channel
    ADD CONSTRAINT channel_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

-- Партиционированная таблица на 313 млн строк. Здесь раньше было написано, что ключ
-- стоит «секунды, а не минуты», и снимать его на заливке не нужно. Замер это опроверг:
-- одна такая проверка на 313 546 016 строк занимает 16–26 минут, три ключа этого файла
-- вместе — от 31 до 78 минут. Это 940 млн обращений к индексу, и кэш тут не спасает.
--
-- Поэтому на ПЕРВИЧНОЙ заливке порядок другой: сначала COPY без ключей, потом
--   ALTER TABLE ... ADD CONSTRAINT ... FOREIGN KEY (...) REFERENCES ... NOT VALID;
--   ALTER TABLE ... VALIDATE CONSTRAINT ...;
-- NOT VALID вешает ключ мгновенно и проверяет только новые строки; VALIDATE проходит
-- старые под слабой блокировкой, не останавливая запись. Разница с обычным ADD
-- CONSTRAINT в том, что база остаётся рабочей, пока идёт проверка.
--
-- Следствие для порядка накатывания: связка schema_events -> schema_xref -> загрузка
-- верна для чистого стенда, но НЕ для продуктивной заливки. Там schema_xref идёт
-- после COPY. Проверка порядка в code/check_schema.py смотрит на зависимости схемы,
-- а не на порядок работ, и этого различия не видит.
--
-- Загрузчик копирует section_id из smvu.channel, так что нарушать ключ ему нечем.
--
-- Колонка nullable сознательно, и это не послабление. NULL получают две группы каналов,
-- у которых участка нет по существу: 765 датчиков внутри диспетчерских пунктов
-- и 1 142 канала-заглушки, которых нет в справочнике заказчика. Если бы колонка была
-- NOT NULL, COPY отверг бы 9,4 млн строк снятого оборудования — 3 % истории.
ALTER TABLE smvu.reading
    ADD CONSTRAINT reading_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE smvu.fault_episode
    ADD CONSTRAINT fault_episode_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE feat.section_daily
    ADD CONSTRAINT section_daily_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE feat.section_features
    ADD CONSTRAINT section_features_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE feat.permit_window
    ADD CONSTRAINT permit_window_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE pred.forecast
    ADD CONSTRAINT forecast_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE pred.forecast_current
    ADD CONSTRAINT forecast_current_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

-- ---------------------------------------------------------------------------
-- 3. Ключи, упёршиеся в порядок файлов
-- ---------------------------------------------------------------------------
-- Заявка -> породивший её прогноз (М-12). Прогноз — журнал, его не удаляют,
-- поэтому NO ACTION.
ALTER TABLE maint.notification
    ADD CONSTRAINT notif_forecast_fk FOREIGN KEY (forecast_id) REFERENCES pred.forecast(forecast_id);

-- Операция заказа ТОиР -> наряд-допуск по его номеру. Наряд удалять нельзя,
-- пока на него ссылается операция.
ALTER TABLE maint.work_order_operation
    ADD CONSTRAINT wo_op_permit_fk FOREIGN KEY (permit_no) REFERENCES permit.permit(number);

-- Вывод датчика из работы под наряд -> канал СМВУ по его тегу. Раньше ключ шёл
-- на smvu.sensor.external_id; таблицы физических датчиков больше нет, в выгрузке
-- заказчика её не оказалось. Канал списали — запись о блокировке в истории наряда
-- остаётся, ссылка обнуляется.
ALTER TABLE permit.permit_detector_inhibit
    ADD CONSTRAINT inhibit_channel_fk FOREIGN KEY (sensor_id) REFERENCES smvu.channel(tag)
    ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- 4. Чего здесь нет и почему
-- ---------------------------------------------------------------------------
-- geo.geo_object.smvu_id -> smvu.channel.tag. Реестр объектов грузится раньше
--   первой выгрузки СМВУ; ключ уронил бы загрузку реестра. Связь канала
--   с участком идёт через section_id, а не через эту колонку.
-- pred.feedback.decided_by, *.created_by, *.approved_by -> ref.app_user.
--   Таблицы пользователей в схеме пока нет (docs/HLD.md разд. 3.5). Появится —
--   ключи ставить сюда же.
-- maint.notification.failure_mode_code и коды каталога ISO 14224 -> ref.catalog_code.
--   Код уникален только внутри (catalog, code_group); проверяет приложение.
