-- 030. Отказ в определении модели v3: словарь значений и эпизоды по нему.
--
-- ЗАЧЕМ. Модель v3 (lgbm-v3-bag-2026.09.21) обучена на метке D5: отказ — эпизод
-- длиннее часа из любого значения словаря «Неисправен», «Батарея неисправна»,
-- «Много неисправных устройств», «Не определено», инциденты склеены окном 60 минут.
-- Определение лежит в contracts/failure.v3.json. Наша проверка М-18…М-20
-- (code/check_metrics.py) до этой миграции считала только эпизоды «Неисправен»
-- из smvu.fault_episode, то есть судила модель по более узкой цели, чем та,
-- на которой её учили. Эпизодов трёх остальных значений в базе не было вовсе:
-- smvu.fault_rule (004_events.sql) их не называет, и построитель их не собирал.
--
-- ПОЧЕМУ ОТДЕЛЬНЫЕ ТАБЛИЦЫ, А НЕ СТРОКИ В smvu.fault_rule И smvu.fault_episode.
-- Ни один из пяти читателей smvu.fault_episode не фильтрует по fault_value:
-- карточка участка (backend/app/api/objects.py), веса участков
-- (028_section_weight.sql), признаки fault_30d и neighbor_fault_7d
-- (backend/app/worker/features.py), code/check_spread.py и сверка с эталоном
-- в построителе. Положи мы эпизоды модели в ту же таблицу — у всех пяти молча
-- выросли бы счётчики. Хуже того, эпизод D5 перекрывает эпизод «Неисправен»
-- того же канала по времени, и ограничение EXCLUDE таблицы отвергло бы вставку.
-- Отдельная пара таблиц не меняет ни одной строки, которую читает экран.
--
-- Построитель — backend/app/ingest/model_failure_episodes.py; его вызывает
-- и backend/app/ingest/fault_episodes.py после построения эпизодов экрана.

-- ---------------------------------------------------------------------------
-- 1. Словарь значений модели
-- ---------------------------------------------------------------------------
-- Правило не зависит от типа датчика, в отличие от smvu.fault_rule: модель
-- ставит метку по значению журнала у любого канала, включая 1 142 заглушки
-- без типа. Поэтому ключ — одно значение, а не пара (тип, значение).
CREATE TABLE smvu.model_failure_value (
    fault_value          text    PRIMARY KEY,
    -- Какая модель учится на этом значении. Сменится модель — строки
    -- перезаводятся новой миграцией вместе с contracts/failure.vN.json.
    model_version        text    NOT NULL,
    -- Код метки у ML-команды (D5). Не ключ: справочника определений у нас нет.
    definition           text    NOT NULL,
    -- Эпизод короче порога — дребезг, а не отказ. Порог в контракте один
    -- на всё определение; здесь он повторён в каждой строке, чтобы построитель
    -- соединялся по значению так же, как с smvu.fault_rule.
    min_duration_seconds integer NOT NULL CHECK (min_duration_seconds > 0)
);

COMMENT ON TABLE smvu.model_failure_value IS
    'Значения журнала, которые модель v3 считает отказом (метка D5). Источник — contracts/failure.v3.json. Экранное правило — smvu.fault_rule, эта таблица его не меняет';

-- Четыре строки — дословно failure_values из contracts/failure.v3.json.
-- Совпадение проверяет code/tests/test_model_failure.py.
INSERT INTO smvu.model_failure_value
       (fault_value, model_version, definition, min_duration_seconds) VALUES
    ('Неисправен',                  'lgbm-v3-bag-2026.09.21', 'D5', 3600),
    ('Батарея неисправна',          'lgbm-v3-bag-2026.09.21', 'D5', 3600),
    ('Много неисправных устройств', 'lgbm-v3-bag-2026.09.21', 'D5', 3600),
    ('Не определено',               'lgbm-v3-bag-2026.09.21', 'D5', 3600);

-- ---------------------------------------------------------------------------
-- 2. Эпизоды по словарю модели
-- ---------------------------------------------------------------------------
-- Форма та же, что у smvu.fault_episode (004 и 017): одинаковые колонки
-- позволяют сверять таблицы одним запросом. Плюс model_version — по ней
-- code/check_metrics.py берёт эпизоды ровно той модели, что названа в контракте.
CREATE TABLE smvu.model_failure_episode (
    episode_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id    integer     NOT NULL REFERENCES smvu.channel,
    section_id    integer     REFERENCES ref.object_xref(section_id),
    started_at    timestamptz NOT NULL,
    -- NULL — эпизод не закрыт к концу архива. Модель такой эпизод считает
    -- отказом (keep_open в src/ml/failure_defs.py), если он уже длиннее порога.
    ended_at      timestamptz,
    rows_cnt      integer     NOT NULL DEFAULT 1,
    closed_by     text,
    -- Значение первой записи эпизода; внутри эпизода значения словаря могут
    -- сменять друг друга.
    fault_value   text        NOT NULL REFERENCES smvu.model_failure_value,
    spans_outage  boolean     NOT NULL DEFAULT false,
    model_version text        NOT NULL,
    EXCLUDE USING gist (channel_id WITH =, tstzrange(started_at, ended_at) WITH &&)
);

CREATE INDEX model_failure_episode_started_idx
    ON smvu.model_failure_episode (started_at);

COMMENT ON TABLE smvu.model_failure_episode IS
    'Эпизоды отказа по словарю модели v3 (smvu.model_failure_value). Цель М-18…М-20. Экран читает smvu.fault_episode, эту таблицу — нет';
