-- schema_xref.sql — перекодировка участка и все ключи между схемами.
-- Это миграция 010_xref из docs/HLD.md разд. 5.4. Накатывается ПОСЛЕДНЕЙ:
--   schema_assets.sql -> schema_geo.sql -> schema_permits.sql -> schema_events.sql -> этот файл.
--
-- Зачем отдельный файл. Один и тот же участок коллектора в четырёх схемах зовётся
-- по-разному (docs/HLD.md разд. 5.3): smvu/feat/pred — section_id integer,
-- geo — object_id uuid, asset — func_location.id bigint, permit — location.id bigint.
-- Таблица перекодировки ссылается сразу на три схемы, а на неё ссылаются ещё семь
-- таблиц из четвёртой. Положить её в любой из четырёх файлов нельзя: файл начнёт
-- ссылаться на то, чего при его накатывании ещё нет. Сюда же собраны три ключа,
-- которые упёрлись в порядок файлов: заявка -> прогноз, операция заказа -> наряд,
-- блокировка датчика под наряд -> датчик.

CREATE SCHEMA IF NOT EXISTS ref;   -- уже есть после schema_assets.sql, но файл обязан быть самодостаточным

-- ---------------------------------------------------------------------------
-- 1. Участок: один короткий ключ на четыре длинных
-- ---------------------------------------------------------------------------
-- section_id — integer, а не uuid, потому что стоит в горячем пути: 18 млн строк
-- событий и 5,4 млн строк свёртки. 4 байта против 16 — 216 МБ разницы в куче
-- и столько же в индексах (docs/HLD.md разд. 5.3).
--
-- Участок, для которого перекодировки ещё нет. В выгрузке СМВУ место — это адрес
-- текстом. Загрузчик на каждый новый адрес заводит строку здесь с одним только
-- smvu_address, а три ссылки оставляет пустыми, пока диспетчер не разберёт
-- geo.geo_unresolved. Так историческая загрузка не падает на неизвестном участке,
-- строка не теряется и не получает координату (0,0):
--
--   INSERT INTO ref.object_xref (smvu_address) VALUES ($1)
--   ON CONFLICT (smvu_address) DO UPDATE SET smvu_address = excluded.smvu_address
--   RETURNING section_id;
--
-- GENERATED BY DEFAULT, а не ALWAYS: если заказчик отдаст реестр участков со своими
-- номерами, их можно вставить как есть, а новые адреса дальше нумерует база.
CREATE TABLE ref.object_xref (
    section_id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Три ссылки в чужие схемы. ON DELETE SET NULL: участок с историей событий
    -- переживает удаление своей записи в геореестре, ТОиР или нарядах.
    geo_object_id      uuid   UNIQUE REFERENCES geo.geo_object(object_id)     ON DELETE SET NULL,
    func_location_id   bigint UNIQUE REFERENCES asset.func_location(id)       ON DELETE SET NULL,
    permit_location_id bigint UNIQUE REFERENCES permit.location(id)           ON DELETE SET NULL,
    smvu_address       text   UNIQUE,     -- адрес текстом, как в выгрузке СМВУ
    inventory_no       text,              -- номер по реестру ОЭ, для сверки руками
    -- Строка без единого опознавательного признака бессмысленна.
    CHECK (num_nonnulls(geo_object_id, func_location_id, permit_location_id,
                        smvu_address, inventory_no) > 0)
);

COMMENT ON TABLE ref.object_xref IS
    'Перекодировка участка коллектора: канонический section_id против ключей geo, asset, permit и адреса СМВУ';

-- ---------------------------------------------------------------------------
-- 2. Ключи section_id -> ref.object_xref
-- ---------------------------------------------------------------------------
-- ON DELETE не указан = NO ACTION: участок с событиями или прогнозами удалить
-- нельзя, сначала надо решить, куда девать его историю.
ALTER TABLE smvu.sensor
    ADD CONSTRAINT sensor_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

-- Партиционированная таблица на 18 млн строк. Ключ — одна проверка по таблице из
-- 4125 строк в кэше на каждую вставку, на первичной заливке это секунды, а не минуты,
-- снимать его вместе с индексами (schema_events.sql разд. 3) не нужно. Загрузчик
-- копирует section_id из smvu.sensor, так что нарушать ключ ему нечем.
ALTER TABLE smvu.event
    ADD CONSTRAINT event_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE feat.section_daily
    ADD CONSTRAINT section_daily_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE feat.section_features
    ADD CONSTRAINT section_features_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE feat.permit_window
    ADD CONSTRAINT permit_window_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE pred.forecast
    ADD CONSTRAINT forecast_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

ALTER TABLE pred.forecast_current
    ADD CONSTRAINT forecast_current_section_fk FOREIGN KEY (section_id) REFERENCES ref.object_xref(section_id);

-- ---------------------------------------------------------------------------
-- 3. Ключи, упёршиеся в порядок файлов
-- ---------------------------------------------------------------------------
-- Заявка -> породивший её прогноз (М-12). Прогноз — журнал, его не удаляют,
-- поэтому NO ACTION.
ALTER TABLE maint.notification
    ADD CONSTRAINT notif_forecast_fk FOREIGN KEY (forecast_id) REFERENCES pred.forecast(forecast_id);

-- Операция заказа ТОиР -> наряд-допуск по его номеру. Наряд удалять нельзя,
-- пока на него ссылается операция.
ALTER TABLE maint.work_order_operation
    ADD CONSTRAINT wo_op_permit_fk FOREIGN KEY (permit_no) REFERENCES permit.permit(number);

-- Вывод датчика из работы под наряд -> датчик по его внешнему идентификатору.
-- Датчик списали — запись о блокировке в истории наряда остаётся, ссылка обнуляется.
ALTER TABLE permit.permit_detector_inhibit
    ADD CONSTRAINT inhibit_sensor_fk FOREIGN KEY (sensor_id) REFERENCES smvu.sensor(external_id)
    ON DELETE SET NULL;

-- ---------------------------------------------------------------------------
-- 4. Чего здесь нет и почему
-- ---------------------------------------------------------------------------
-- geo.geo_object.smvu_id -> smvu.sensor.external_id. Реестр объектов грузится
--   раньше первой выгрузки СМВУ; ключ уронил бы загрузку реестра. Связь датчика
--   с участком идёт через section_id, а не через эту колонку.
-- pred.feedback.decided_by, *.created_by, *.approved_by -> ref.app_user.
--   Таблицы пользователей в схеме пока нет (docs/HLD.md разд. 3.5). Появится —
--   ключи ставить сюда же.
-- maint.notification.failure_mode_code и коды каталога ISO 14224 -> ref.catalog_code.
--   Код уникален только внутри (catalog, code_group); проверяет приложение.
