-- schema_events.sql — события СМВУ, телеметрия, признаки и прогнозы
-- PostgreSQL 15+ (нативное декларативное партиционирование), расширения: btree_gist.
-- Целевая версия поставки: 18.6 (образ postgis/postgis:18-3.6).
-- PostGIS здесь не нужен: геометрия живёт в schema_geo.sql, сюда приходит только section_id.
-- TimescaleDB НЕ требуется. Если заказчик отдаст сырую телеметрию и smvu.reading
-- перевалит за 300–500 млн строк — см. комментарий в разделе 4 этого файла.
--
-- Целевое железо, под которое всё считалось: 4 ядра, 16 ГБ ОЗУ, SATA SSD.
-- Настройки сервера, от которых зависят оценки времени:
--   shared_buffers = 4GB, effective_cache_size = 12GB, work_mem = 64MB,
--   maintenance_work_mem = 1GB, max_parallel_workers_per_gather = 2,
--   max_wal_size = 8GB, checkpoint_timeout = 15min, random_page_cost = 1.1

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE SCHEMA IF NOT EXISTS smvu;   -- сырьё: события и показания
CREATE SCHEMA IF NOT EXISTS feat;   -- предрасчёт: суточные свёртки и вектор признаков
CREATE SCHEMA IF NOT EXISTS pred;   -- прогнозы и журнал расчётов

-- ---------------------------------------------------------------------------
-- 1. Справочники
-- ---------------------------------------------------------------------------

CREATE TABLE smvu.event_type (
    type_code    text PRIMARY KEY,             -- 'CH4_HIGH', 'FLOOD', 'DOOR_OPEN', ...
    type_name    text NOT NULL,
    system_code  text NOT NULL,                -- АКМ / ОПС / СКУД / вентиляция
    is_alarm     boolean NOT NULL DEFAULT true,
    comment      text
);

-- Датчик. Один физический прибор = одна строка. Ключ склейки с реестром оборудования —
-- equipment_id из asset.equipment (schema_assets.sql). Если склейка не состоялась,
-- equipment_id остаётся NULL, а датчик всё равно попадает в модель по section_id.
CREATE TABLE smvu.sensor (
    sensor_id      integer PRIMARY KEY,
    external_id    text NOT NULL UNIQUE,       -- как датчик зовут в выгрузке СМВУ
    equipment_id   text,                       -- -> asset.equipment.equipment_id
    section_id     integer NOT NULL,           -- -> geo_object, участок 200 м
    sensor_type    text NOT NULL,              -- ДМТ-6, ТК-1, СЕНСИС-500, МОД, СИГМА-1, БСМ
    installed_at   date,
    removed_at     date,
    is_active      boolean NOT NULL DEFAULT true
);

CREATE INDEX sensor_section_idx ON smvu.sensor (section_id) WHERE is_active;

-- ---------------------------------------------------------------------------
-- 2. События СМВУ — главная таблица. Партиции помесячные.
-- ---------------------------------------------------------------------------
-- Почему помесячно, а не понедельно: 12 лет × 12 = 144 партиции. Планировщик отбрасывает
-- лишние партиции за единицы миллисекунд. При недельных партициях их было бы 626,
-- и планирование запроса начало бы стоить дороже самого запроса.

CREATE TABLE smvu.event (
    event_id     bigint GENERATED BY DEFAULT AS IDENTITY,
    event_time   timestamptz NOT NULL,
    sensor_id    integer     NOT NULL REFERENCES smvu.sensor,
    section_id   integer     NOT NULL,          -- денормализация: копия sensor.section_id
    type_code    text        NOT NULL REFERENCES smvu.event_type,
    value_num    real,                          -- показание в момент события, если есть
    check_result smallint,                      -- NULL = не проверяли, 0 = ложная, 1 = подтверждена
    checked_at   timestamptz,
    source_batch bigint,                        -- -> load.batch, из какого файла строка
    PRIMARY KEY (event_id, event_time)
) PARTITION BY RANGE (event_time);

-- section_id продублирован сознательно. Без него любой запрос «события по участку»
-- тянет join с smvu.sensor на каждую партицию. Плата — 4 байта на строку,
-- на 18 млн строк это 72 МБ.
-- Заполняет его загрузчик при разборе staging, а НЕ триггер: построчный триггер
-- на 18 млн строк COPY сожрёт больше времени, чем сэкономит весь этот индекс.
-- Расхождение ловим ночной сверкой:
--   SELECT count(*) FROM smvu.event e JOIN smvu.sensor s USING (sensor_id)
--    WHERE e.section_id <> s.section_id;   -- обязано быть 0

-- Партиции. В проде их заводит pg_partman (см. вызов в конце файла) либо cron-скрипт.
CREATE TABLE smvu.event_2014_01 PARTITION OF smvu.event
    FOR VALUES FROM ('2014-01-01') TO ('2014-02-01');
CREATE TABLE smvu.event_default PARTITION OF smvu.event DEFAULT;

-- ---------------------------------------------------------------------------
-- 3. Индексы на событиях
-- ---------------------------------------------------------------------------
-- Индексы создаём НА РОДИТЕЛЕ: Postgres 11+ каскадирует их на все партиции,
-- включая будущие. Но при первичной заливке 12 лет их надо снять и создать заново
-- после COPY — иначе загрузка идёт втрое дольше (см. load_smvu_xlsx.py).

-- 3.1. BRIN по времени. Таблица append-only, строки ложатся почти в хронологическом
-- порядке, корреляция физического порядка со временем близка к 1 — это ровно тот случай,
-- под который BRIN сделан. Замер Cybertec на 5 млрд строк: btree 105 ГБ против BRIN 7 МБ.
-- У нас на 18 млн строк это примерно 500 МБ btree против 30 КБ BRIN.
-- pages_per_range = 32 вместо дефолтных 128: Crunchy намерили, что на их таблице
-- сужение диапазона ускорило точечную выборку с 11 мс до 4 мс, а на широких
-- диапазонах разницы нет.
CREATE INDEX event_time_brin ON smvu.event USING brin (event_time) WITH (pages_per_range = 32);

-- 3.2. Композитный btree под «события по датчику за период» — сценарий карточки датчика.
-- BRIN тут не работает: строки одного датчика размазаны по всей таблице.
CREATE INDEX event_sensor_time_idx ON smvu.event (sensor_id, event_time DESC);

-- 3.3. «События по участку за период» — сценарий карточки участка и сборки признаков.
CREATE INDEX event_section_time_idx ON smvu.event (section_id, event_time DESC);

-- 3.4. Частичный индекс под разметку: непроверенные события — это те, по которым
-- модель не знает исхода. Их единицы процентов от таблицы, индекс выходит крошечный.
CREATE INDEX event_unchecked_idx ON smvu.event (event_time DESC)
    WHERE check_result IS NULL;

-- 3.5. Частичный индекс под обучающую выборку: подтверждённые аварии.
CREATE INDEX event_confirmed_idx ON smvu.event (section_id, event_time)
    WHERE check_result = 1;

-- ---------------------------------------------------------------------------
-- 4. Телеметрия (заводим, только если заказчик отдаст поток показаний, а не одни тревоги)
-- ---------------------------------------------------------------------------
-- Строка нарочно узкая: 4 + 8 + 4 + 2 = 18 байт полезных, ~48 байт с заголовком строки.
-- Дискретность — 1 минута. Тоньше смысла нет: время срабатывания датчика метана
-- по регламенту 8–15 с, и «секундная» телеметрия описывала бы шум прибора, а не процесс.
CREATE TABLE smvu.reading (
    sensor_id  integer     NOT NULL,
    read_time  timestamptz NOT NULL,
    value_num  real        NOT NULL,
    quality    smallint    NOT NULL DEFAULT 0,  -- 0 ок, 1 подозрение, 2 брак
    PRIMARY KEY (sensor_id, read_time)
) PARTITION BY RANGE (read_time);

CREATE TABLE smvu.reading_default PARTITION OF smvu.reading DEFAULT;
CREATE INDEX reading_time_brin ON smvu.reading USING brin (read_time) WITH (pages_per_range = 32);

-- Порог, после которого я бы ставил TimescaleDB: когда smvu.reading перешагнёт
-- 300 млн строк ИЛИ когда полное сканирование месячной партиции перестанет укладываться
-- в 30 секунд. До этого хватает партиций + BRIN, а расширение под лицензией TSL
-- на закрытом контуре заказчика ещё надо согласовать.

-- ---------------------------------------------------------------------------
-- 5. Предрасчёт: суточная свёртка по участку
-- ---------------------------------------------------------------------------
-- Это ручной аналог continuous aggregate из TimescaleDB. Разница в том, что тут
-- я сам решаю, когда и какой кусок пересчитать, и мне не нужно расширение.
-- Размер: 4125 участков × 365 дней × 12 лет = 18,07 млн строк — столько же, сколько
-- событий, но строка втрое уже и читается одним сканом.

CREATE TABLE feat.section_daily (
    section_id      integer NOT NULL,
    day             date    NOT NULL,
    events_total    integer NOT NULL DEFAULT 0,
    events_ch4      integer NOT NULL DEFAULT 0,
    events_flood    integer NOT NULL DEFAULT 0,
    events_fire     integer NOT NULL DEFAULT 0,
    confirmed_total integer NOT NULL DEFAULT 0,
    false_total     integer NOT NULL DEFAULT 0,
    active_sensors  smallint NOT NULL DEFAULT 0,
    silent_sensors  smallint NOT NULL DEFAULT 0,  -- датчики без единой записи за сутки
    max_value       real,
    PRIMARY KEY (section_id, day)
);

CREATE INDEX section_daily_day_idx ON feat.section_daily (day);

-- Инкрементальный пересчёт. Вызываем на окне «вчера и сегодня», а не на всей истории:
-- 2 дня × 4125 участков = 8250 строк вместо 18 млн.
CREATE OR REPLACE FUNCTION feat.refresh_section_daily(p_from date, p_to date)
RETURNS integer AS $$
DECLARE
    n integer;
BEGIN
    INSERT INTO feat.section_daily AS d (
        section_id, day, events_total, events_ch4, events_flood, events_fire,
        confirmed_total, false_total, max_value)
    SELECT e.section_id,
           e.event_time::date,
           count(*),
           count(*) FILTER (WHERE t.system_code = 'АКМ'),
           count(*) FILTER (WHERE e.type_code LIKE 'FLOOD%'),
           count(*) FILTER (WHERE t.system_code = 'ОПС'),
           count(*) FILTER (WHERE e.check_result = 1),
           count(*) FILTER (WHERE e.check_result = 0),
           max(e.value_num)
      FROM smvu.event e
      JOIN smvu.event_type t ON t.type_code = e.type_code
     WHERE e.event_time >= p_from::timestamptz
       AND e.event_time <  (p_to + 1)::timestamptz
     GROUP BY 1, 2
    ON CONFLICT (section_id, day) DO UPDATE SET
        events_total    = excluded.events_total,
        events_ch4      = excluded.events_ch4,
        events_flood    = excluded.events_flood,
        events_fire     = excluded.events_fire,
        confirmed_total = excluded.confirmed_total,
        false_total     = excluded.false_total,
        max_value       = excluded.max_value;
    GET DIAGNOSTICS n = ROW_COUNT;
    RETURN n;
END $$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- 6. Вектор признаков: одна строка на участок, всегда актуальная
-- ---------------------------------------------------------------------------
-- 4125 строк. Таблица целиком влезает в shared_buffers и читается за миллисекунды.
-- Признаки-«окна» (7/30/90/365 дней) считаются из feat.section_daily, а не из событий.
CREATE TABLE feat.section_features (
    section_id      integer PRIMARY KEY,
    computed_at     timestamptz NOT NULL,
    ev_1d           integer,
    ev_7d           integer,
    ev_30d          integer,
    ev_365d         integer,
    confirmed_365d  integer,
    false_rate_365d real,               -- доля ложных срабатываний: признак «датчик врёт»
    days_since_last_event      integer,
    days_since_last_confirmed  integer,
    days_since_last_repair     integer, -- из maint.work_order
    sensor_count    smallint,
    silent_sensor_share real,           -- доля молчащих датчиков: признак «мы ослепли»
    zero_drift_max  real,               -- дрейф нуля метановых датчиков (см. 15-reglament)
    age_years       real,               -- возраст участка из реестра
    criticality     smallint,           -- из ref.criticality
    season_sin      real,
    season_cos      real
);

-- ---------------------------------------------------------------------------
-- 7. Прогнозы и журнал расчётов
-- ---------------------------------------------------------------------------

CREATE TABLE pred.run (
    run_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at    timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz,
    status        text NOT NULL DEFAULT 'running'
                  CHECK (status IN ('running','done','failed','degraded')),
    model_version text NOT NULL,
    objects_total integer,
    -- Разбивка бюджета пяти минут. Без неё нечего показывать на приёмке и нечем
    -- доказывать, какая стадия просела, когда расчёт не уложится.
    ms_fetch      integer,
    ms_aggregate  integer,
    ms_features   integer,
    ms_inference  integer,
    ms_explain    integer,
    ms_write      integer,
    error_text    text
);

CREATE TABLE pred.forecast (
    run_id       bigint  NOT NULL REFERENCES pred.run,
    section_id   integer NOT NULL,
    horizon_h    smallint NOT NULL,      -- 24 и более
    probability  real     NOT NULL,
    risk_rank    integer  NOT NULL,
    factors      jsonb    NOT NULL,      -- топ-5 вкладов признаков: [{"f":"ev_7d","v":0.31}, ...]
    PRIMARY KEY (run_id, section_id)
);

CREATE INDEX forecast_rank_idx ON pred.forecast (run_id, risk_rank);

-- Текущий прогноз — то, что отдаёт API на каждый чих. Одна строка на участок,
-- переписывается в конце расчёта одной транзакцией.
CREATE TABLE pred.forecast_current (
    section_id   integer PRIMARY KEY,
    run_id       bigint  NOT NULL REFERENCES pred.run,
    computed_at  timestamptz NOT NULL,
    horizon_h    smallint NOT NULL,
    probability  real NOT NULL,
    risk_rank    integer NOT NULL,
    is_stale     boolean NOT NULL DEFAULT false,  -- true = отдаём вчерашнее, расчёт не прошёл
    factors      jsonb NOT NULL
);

CREATE INDEX forecast_current_rank_idx ON pred.forecast_current (risk_rank);

-- ---------------------------------------------------------------------------
-- 8. Джойн событий с нарядами-допусками по времени и месту
-- ---------------------------------------------------------------------------
-- Задача: «была ли на участке бригада в момент срабатывания». Наивный джойн
-- по BETWEEN заставляет планировщик делать nested loop с полным сканом нарядов.
-- Лечится диапазонным типом + GiST-индексом из btree_gist: по одному индексу
-- проверяются и участок (btree-часть), и пересечение интервалов (gist-часть).

CREATE TABLE permit_window (
    permit_id   bigint PRIMARY KEY,
    section_id  integer NOT NULL,
    valid       tstzrange NOT NULL,
    work_kind   text NOT NULL,
    EXCLUDE USING gist (section_id WITH =, valid WITH &&)  -- заодно запрет двух нарядов внахлёст
);

CREATE INDEX permit_window_gist ON permit_window USING gist (section_id, valid);

-- Запрос, который после этого работает по индексу:
--   SELECT e.event_id, p.permit_id
--     FROM smvu.event e
--     LEFT JOIN permit_window p
--       ON p.section_id = e.section_id AND p.valid @> e.event_time
--    WHERE e.event_time >= now() - interval '7 days';

-- ---------------------------------------------------------------------------
-- 9. Опорные запросы, под которые всё это заточено
-- ---------------------------------------------------------------------------

-- 9.1. Текущий риск всех объектов — главный запрос интерфейса диспетчера.
-- Читает 4125 строк из кэша, без единого обращения к событиям.
--   SELECT section_id, probability, risk_rank, is_stale FROM pred.forecast_current
--    ORDER BY risk_rank LIMIT 50;

-- 9.2. События по датчику за период — идёт по event_sensor_time_idx.
--   SELECT event_time, type_code, value_num FROM smvu.event
--    WHERE sensor_id = $1 AND event_time >= $2 AND event_time < $3
--    ORDER BY event_time DESC LIMIT 200;

-- 9.3. Признаки-окна из суточной свёртки — один скан 4125 × 365 строк.
--   SELECT section_id,
--          sum(events_total) FILTER (WHERE day > current_date - 7)  AS ev_7d,
--          sum(events_total) FILTER (WHERE day > current_date - 30) AS ev_30d,
--          sum(events_total)                                        AS ev_365d
--     FROM feat.section_daily
--    WHERE day > current_date - 365
--    GROUP BY section_id;

-- ---------------------------------------------------------------------------
-- 10. pg_partman: автоматика нарезки партиций
-- ---------------------------------------------------------------------------
-- Расширение не даёт ничего, кроме избавления от самописного крона. Если DBA заказчика
-- не хочет ставить лишнее — тридцать строк на plpgsql делают то же самое.
--
-- CREATE EXTENSION pg_partman SCHEMA partman;
-- SELECT partman.create_parent(
--     p_parent_table => 'smvu.event',
--     p_control      => 'event_time',
--     p_interval     => '1 month',
--     p_premake      => 3);
-- UPDATE partman.part_config SET retention = NULL WHERE parent_table = 'smvu.event';
-- -- retention = NULL: ничего не удаляем. 12 лет истории — это обучающая выборка,
-- -- а не мусор. Двенадцать гигабайт диска дешевле переобучения на укороченной истории.
